spring:
  application:
    name: crypto-bot
  data:
    redis:
      host: localhost
      port: 6379

binance:
  api:
  secret:

telegram:
  bot:
    username:
    token:

logging:
  level:
    root: INFO